export const FETCH_POSTS = 'FETCH_POSTS';
export const FILTER_POSTS = 'FILTER_POSTS';
export const VOTE_POST = 'VOTE_POST';
export const TOGGLE_ADD_POST_MODAL = 'TOGGLE_ADD_POST_MODAL';
export const SAVE_POST = 'SAVE_POST';
export const UPDATE_POST = 'UPDATE_POST';
export const FETCH_POST_COMMENTS = 'FETCH_POST_COMMENTS';