export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const SAVE_COMMENT = 'SAVE_COMMENT';
export const UPDATE_COMMENT = 'UPDATE_COMMENT';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const VOTE_COMMENT = 'VOTE_COMMENT';